### ISSUE TITLE
message localization for post generated errors

### ISSUE THREAD

**Issue by aurium** [calidion/errorable#1]
At you example you run:
```javascript
var errors = new Generator(json, 'zh-CN').errors;
```
And that allows:
```javascript
throw errors.ILoveYou
```

Nice! However i may be using a module that uses Errorable, and that can't _(or don't know how)_ access my `lang` definition. So... Wold be nice if error objects from Errorable come with a `l10n` method, allowing me to translate errors from third part modules with Errorable output.

```javascript
require('do-you-love-me')('Augusta Ada Byron', function(err, intensity){
  if (err) throw err.i10n(currentLang);
  ...
});
```

**Comment by calidion** [comment]
@aurium 
added method localize for this purpose with commit : https://github.com/calidion/errorable/commit/b99ed9e943494930ee832639e276620fefc439cb
thank you.
